server:
  port: 3003
  servlet:
    context-path: /notifications

app:
  api-key: ${BREVO_API_KEY}
  email: "nrin31266@gmail.com"

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://nrin31266:16092005@localhost:27017/kanban-notification?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: <key>
