version: "3.8"

#networks:
#  kanban-network:
#    driver: bridge
networks:
  prj1:
    external: true  # Chỉ định mạng bên ngoài

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-kanban
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity-service-kanban
      MYSQL_USER: nrin31266
      MYSQL_PASSWORD: 16092005
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - prj1
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka-kanban
    hostname: localhost
    ports:
      - '9092:9092'  # Added listener port
      - '9093:9093'  # Added controller port
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - prj1
  mysqladmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysqladmin-kanban
    ports:
      - "8001:80"
    networks:
      - prj1
    environment:
      - PMA_HOST=mysql
      - PMA_POST=3306


volumes:
  mongo_data:
  mysql-data:
  mongo_config:
