version: "3"

networks:
  kanban-network:
    driver: bridge

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-kanban
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nrin31266
      MONGO_INITDB_ROOT_PASSWORD: 16092005
      MONGO_INITDB_DATABASE: kanban
    networks:
      - kanban-network
  mysql:
    image: mysql:8.0
    container_name: mysql-kanban
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity-service-kanban
      MYSQL_USER: nrin31266
      MYSQL_PASSWORD: 16092005
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kanban-network
volumes:
  mongo_data:
  mysql-data:
