server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service-kanban
          uri: http://localhost:3001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: kanban-service
          uri: http://localhost:3002
          predicates:
            - Path=${app.api-prefix}/kanban/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:3003
          predicates:
            - Path=${app.api-prefix}/notifications/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:3005
          predicates:
            - Path=${app.api-prefix}/profiles/**
          filters:
            - StripPrefix=2
        - id: location-service
          uri: http://localhost:3007
          predicates:
            - Path=${app.api-prefix}/locations/**
          filters:
            - StripPrefix=2

