server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: kanban-service
          uri: http://localhost:3001
          predicates:
            - Path=${app.api-prefix}/**
          filters:
            - StripPrefix=2

