spring:
  application:
    name: kanban-service
  data:
    mongodb:
      uri: mongodb://nrin31266:16092005@localhost:27017/kanban?authSource=admin
      authentication-database: admin

jwt:
  signerKey: HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV

server:
  port: 3001
  servlet:
    context-path: /kanban

firebase:
  config:
    path:
      classpath: firebase/credentials.json
