spring:
  application:
    name: kanban-service
  data:
    mongodb:
#      uri: mongodb://nrin31266:16092005@localhost:27017/kanban?authSource=admin
      auto-index-creation: true
      uri: mongodb+srv://nrin31266:16092005@cluster0.kdpwd.mongodb.net/kanban?retryWrites=true&w=majority&appName=Cluster0
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 3002
  servlet:
    context-path: /kanban

app:
  services:
    profiles: http://localhost:3005/profiles
