spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://nrin31266:16092005@localhost:27017/kanban-payment?authSource=admin
      auto-index-creation: true



server:
  port: 3006
  servlet:
    context-path: /payments