spring:
  application:
    name: kanban-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service-kanban
    driverClassName: com.mysql.cj.jdbc.Driver
    username: nrin31266
    password: 16092005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: ${SIGNER_KEY}

server:
  port: 3001
  servlet:
    context-path: /identity

outbound:
  identity:
    client-id: ${GG_CLIENT_ID}
    client-secret: ${GG_CLIENT_SECRET}
    redirect-uri: ${GG_REDIRECT_URI}


