spring:
  application:
    name: kanban-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service-kanban
    driverClassName: com.mysql.cj.jdbc.Driver
    username: nrin31266
    password: 16092005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV

server:
  port: 3001
  servlet:
    context-path: /kanban

firebase:
  config:
    path:
      classpath: firebase/credentials.json
