spring:
  application:
    name: kanban-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity-service-kanban
    driverClassName: com.mysql.cj.jdbc.Driver
    username: nrin31266
    password: 16092005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV

server:
  port: 3001
  servlet:
    context-path: /identity

outbound:
  identity:
    client-id: "427147667603-bodrqv4jh0148qag2cegph5dh7k8djbv.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3004/auth/authenticate"
