server:
  port: 3005
  servlet:
    context-path: /profiles

spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://nrin31266:16092005@localhost:27017/kanban-profile?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

